### ISSUE TITLE
Add version of binary that is built with `CXXFLAGS=-DALTERNATIVE_TASK_SWITCHER`

### ISSUE THREAD

**Issue by macintacos** [Dimentium/homebrew-autoraise#1]
Building it with that allows "alternative" task switchers (basically, anything that brings an app to the foreground) to use the `warp` feature effectively.

**Comment by Dimentium** [comment]
> Building it with that allows "alternative" task switchers (basically, anything that brings an app to the foreground) to use the `warp` feature effectively.

now you can make:
```brew install autoraise --with-dalternative_task_switcher```
