### ISSUE TITLE
No icon in menu bar?

### ISSUE THREAD

**Issue by jourdanritchey** [Dimentium/homebrew-autoraise#12]
Installing from the .dmg places an icon in the menu bar to toggle whether AutoRaise will focus windows or not. Installing from this tap does not. Is it possible to get a version or flag to provide the menu bar icon?

**Comment by sbmpost** [comment]
@jourdanritchey 
A little late reply, however brew formulas only support compilation and building the binary as an installation flow. The dmg binary depends on Xcode and is pre-compiled. Therefore it can't be deployed via brew.

**Comment by Dimentium** [comment]
> Installing from the .dmg places an icon in the menu bar to toggle whether AutoRaise will focus windows or not. Installing from this tap does not. Is it possible to get a version or flag to provide the menu bar icon?
hi 

I added the cask. 

use:
```
brew tap dimentium/autoraise
brew install --cask dimentium/autoraise/autoraiseapp
```

**Comment by sbmpost** [comment]
@Dimentium 

Interesting. I may have to update the README then.

**Comment by sbmpost** [comment]
Closing this issue because of the solution provided by @Dimentium
