### ISSUE TITLE
Warning: Calling plist_options is deprecated! Use service.require_root instead.

### ISSUE THREAD

**Issue by tracure1337** [Dimentium/homebrew-autoraise#5]
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the dimentium/autoraise tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/dimentium/homebrew-autoraise/autoraise.rb:29

**Comment by fredngo** [comment]
There's already an open PR for this waiting to be reviewed:

https://github.com/Dimentium/homebrew-autoraise/pull/4

**Comment by fredngo** [comment]
Fixed in https://github.com/Dimentium/homebrew-autoraise/pull/4
