### ISSUE TITLE
Question: adding flags to autoraise.

### ISSUE THREAD

**Issue by bdmorin** [Dimentium/homebrew-autoraise#6]
What would be the correct method to add flags to 
```
<string>/opt/homebrew/opt/autoraise/bin/AutoRaise</string>
```

I would like to just add `focusDelay`

Thank you!

**Comment by jmechnich** [comment]
You are probably talking about `homebrew.mxcl.autoraise.plist` and the part where it says:
```
...
    <key>ProgramArguments</key>
    <array>
    <string>/opt/homebrew/opt/autoraise/bin/AutoRaise</string>
    </array>
...
```

You could probably write something like:
```
    <array>
    <string>/opt/homebrew/opt/autoraise/bin/AutoRaise</string>
    <string>-focusDelay</string>
    <string>1</string>
    </array>
```

The better solution is to follow the instructions [here](https://github.com/sbmpost/AutoRaise) and use a configuration file at `~/.AutoRaise` or `~/.config/AutoRaise/config`.
That way your settings will survive any updates to AutoRaise.
